apiVersion: v1
kind: Service
metadata:
  name: selenium-server-service
  labels:
    appClass: selenium-server-service
  namespace: taf
spec:
  type: ClusterIP
  selector:
    appClass: selenium-hub
  ports:
  - name: publish
    port: 4442
    targetPort: 4442
  - name: subscribe
    port: 4443
    targetPort: 4443
  - name: http
    port: 4444
    targetPort: 4444
