apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-selenium-team-4
  namespace: taf
  labels:
    appClass: client-selenium-team-4
spec:
  replicas: 1
  selector:
    matchLabels:
      appClass: client-selenium-team-4
  template:
    metadata:
      labels:
        appClass: client-selenium-team-4
    spec:
      containers:
      - name: client-selenium-team-4
        image: <TO UPDATE>
        env:
          - name: TEST_SERVER
            value: <TO UPDATE>
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 3000
