apiVersion: v1
kind: Service
metadata:
  name: app-selenium-team-1-service
  labels:
    appClass: app-selenium-team-1
  namespace: taf
spec:
  type: LoadBalancer
  selector:
    appClass: app-selenium-team-1
  ports:
  - port: 3000
    targetPort: http
