apiVersion: v1
kind: Service
metadata:
  name: server-selenium-team-4-service
  labels:
    appClass: server-selenium-team-4
  namespace: taf
spec:
  type: LoadBalancer
  selector:
    appClass: server-selenium-team-4
  ports:
  - port: 3000
    targetPort: http